default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  database: letrismo_v2
  password: password

production:
  <<: *default
  host: localhost
  port: 5432
  database: letrismo_v2
  password: <%= Rails.application.credentials.database_password %>
